import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { Inter } from "next/font/google";
import { auth } from "~/server/auth";
import "./globals.css";
import { TRPCProviders } from "./providers";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <SessionProvider session={session}>
          <TRPCProviders>
            <div className="flex h-screen flex-col bg-gray-100 dark:bg-gray-950">
              {children}
            </div>
          </TRPCProviders>
        </SessionProvider>
      </body>
    </html>
  );
}
